language: c
sudo: false
services:
    - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
env:
    global:
        - DISTRO=debian-unstable
        - PACKAGE=rpc
    matrix:
        - OCAML_VERSION=4.02.3
        - OCAML_VERSION=4.03.0
        - OCAML_VERSION=4.04.2 REVDEPS=true
        - OCAML_VERSION=4.05.0
        - OCAML_VERSION=4.06.0
matrix:
    fast_finish: true
    allow_failures:
        - env: OCAML_VERSION=4.06.0
